const {JSDOM}=require('jsdom');
const fs=require('fs'), assert=require('node:assert/strict');
const dom=new JSDOM('<main id="view"></main>',{runScripts:'outside-only'}), w=dom.window;
const source=fs.readFileSync('web/app.js','utf8');
// Validate the whole bundle before exercising individual UI functions.
new (require('node:vm').Script)(source, {filename:'web/app.js'});
w.requestAnimationFrame=fn=>fn();
w.$=s=>w.document.querySelector(s);
w.el=(tag,cls,text)=>{const n=w.document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
w.guard=fn=>fn;w.button=(text,fn,cls)=>{const n=w.el('button',cls,text);n.onclick=fn;return n;};w.iconButton=w.button;
w.selected='work'; w.drafts={};w.peer=null;w.chatStamp='';w.toggleVoice=()=>{};w.uploadAudio=()=>{};w.installThinkingSend=()=>{};w.poll=async()=>{};w.api=async()=>[{id:'discovered-model'}];
const ws={id:'work',ui:{active:'agent-two',tabs:[{id:'chat',kind:'chat'},{id:'agent-two',kind:'chat'}],draft:'first draft',drafts:{'agent-two':'second draft'}},messages:[{role:'user',session:'chat',text:'PRIVATE_OTHER_SESSION'},{role:'user',session:'agent-two',text:'My task',job_id:'j'}]};
w.workspace=()=>ws;w.ui=()=>ws.ui;
w.state={settings:{provider:'codex',model:'test',thinking:'medium'},workspaces:[ws],jobs:[{id:'j',workspace:'work',session:'agent-two',status:'completed',events:[{kind:'request',step:1,prompt:'My task',model:'test',thinking:'medium',context_policy:'files_and_recent_ai',project_files:['task.txt','summary.md'],project_file_tokens:[{path:'task.txt',tokens:60},{path:'summary.md',tokens:40}],part_tokens:{context:100,context_text:100,context_images:0,prompt:10,system:20,instructions:30,recent_ai:0,total:160},system:'System',instructions:'Test command',context_directory:'.',context_note:'Complete selected project files only.',history_turns:3,images:0}]}]};
w.taskMetrics=()=>'';w.speak=()=>{};w.shortTabTitle=x=>x;
const actions=[];w.act=async(name,args)=>{actions.push({name,args});};
w.eval(source.slice(source.indexOf('async function saveDraft('),source.indexOf('async function saveUi(')));
w.eval(source.slice(source.indexOf('const expandedRequests'),source.indexOf('function shortTabTitle(')));
w.eval(source.slice(source.indexOf('function tokenMetrics('),source.indexOf('function renderHistory(')));
assert.equal(w.cleanAgentText('Result<summary>Private continuity notes</summary><score>8</score>'), 'Result');
(async()=>{try{
w.renderChat(); await new Promise(r=>setImmediate(r));
assert.equal(w.$('textarea').value,'second draft');
assert(!w.document.body.textContent.includes('PRIVATE_OTHER_SESSION'));
assert(w.document.body.textContent.includes('What was sent to AI'));
assert(w.document.body.textContent.includes('summary.md'));
const requestParts=w.$('.request-details > .request-part');
assert(requestParts);assert.equal(requestParts.open,false);
assert.deepEqual(Array.from(requestParts.querySelectorAll(':scope > details > summary')).slice(0,4).map(n=>n.textContent.split(' · ')[0]),['Context files sent to AI','User prompt','System prompt','Instruction prompt']);
assert.match(requestParts.textContent,/Context files sent to AI · 100 estimated tokens/);
w.state.jobs[0].events[0].project_file_tokens=[{path:'task.txt',tokens:60},{path:'summary.md',tokens:40}];
w.state.jobs[0].events[0].part_tokens={context:100,prompt:10,system:20,instructions:30,total:160};
w.chatStamp='';w.updateChat();
assert.match(w.$('.request-details > .request-part > summary').textContent,/160 estimated tokens/);
const contextPart=w.$('.request-details > .request-part > details');
assert.match(contextPart.querySelector('summary').textContent,/100 estimated tokens/);
contextPart.open=true;contextPart.dispatchEvent(new w.Event('toggle'));
w.state.jobs[0].events.push({kind:'review',score:7});w.updateChat();
assert.equal(w.$('.request-details > .request-part > details').open,true);
assert.equal(w.$('.composer-model').options.length,2);
// Polling/global navigation must not make the existing view read another session.
ws.ui.active='chat';w.chatStamp='';w.updateChat();
assert(!w.document.body.textContent.includes('PRIVATE_OTHER_SESSION'));
ws.ui.active='agent-two';
const messages=w.$('#messages');
Object.defineProperties(messages,{scrollHeight:{value:2000},clientHeight:{value:400}});
messages.scrollTop=1600;
w.state.jobs[0].events.push({kind:'request',step:2,provider:'test',project_files:[],context_policy:'files_only',part_tokens:{context:12,total:30}});
w.updateChat();assert.equal(messages.scrollTop,1600,'new requests must preserve position even at the bottom');
assert.match(messages.textContent,/Context labels and formatting/);
messages.scrollTop=700;messages.onscroll();
w.$('#view').replaceChildren();w.chatStamp='';w.renderChat();
assert.equal(w.$('#messages').scrollTop,700);
assert.equal(w.$('#stop-job').textContent,'■');
const details=w.$('.request-details');details.open=true;details.dispatchEvent(new w.Event('toggle'));
w.state.jobs[0].events.push({kind:'review',score:8});w.updateChat();assert(w.$('.request-details').open);
w.state.jobs[0].events.push({kind:'tool',name:'shell',arguments:{command:'echo hello'}});
w.updateChat();
const toolRow=w.$('details[data-agent-detail]');assert(toolRow);toolRow.open=true;
w.state.jobs[0].events.push({kind:'text',text:'## Results\n**Completed** successfully.\n\n```sh\necho hello\n```'});
w.updateChat();assert(w.$('details[data-agent-detail]').open);
assert.equal(w.$('.event-answer h2').textContent,'Results');
assert.equal(w.$('.event-answer strong').textContent,'Completed');
assert.equal(w.$('.event-answer pre code').textContent.trim(),'echo hello');
assert.equal(w.$('.agent-activity').tagName,'SECTION');
w.$('details[data-agent-detail]').open=false;
w.state.jobs[0].events.push({kind:'text',text:'Next update'});w.updateChat();
assert.equal(w.$('details[data-agent-detail]').open,false);
const unsafe=w.renderMarkdown('<script>bad()</script> [bad](javascript:alert(1))');
assert(!unsafe.querySelector('script'));assert(!unsafe.querySelector('a[href^="javascript:"]'));
w.$('textarea').value='new task';await w.$('form').onsubmit({preventDefault(){}});
assert.equal(actions.find(a=>a.name==='run').args.session,'agent-two');
assert.equal(ws.ui.draft,'first draft');assert.equal(ws.ui.drafts['agent-two'],'');
let menu;w.showMenu=(_,items)=>menu=items;w.newTerminal=()=>{};w.newWebview=()=>{};w.openTab=(...args)=>actions.push(args);
w.eval(source.slice(source.indexOf('function newTabMenu('),source.indexOf('\nfunction render()')));
w.newTabMenu(null);await menu.find(i=>i.label==='Agent').run();assert.match(actions.at(-1)[2].id,/^agent-/);
const log=w.renderAgentEvents([{kind:'model',step:1,provider:'codex'},{kind:'review',score:null},{kind:'text',text:'A joke. <score>10</score><done><done>'},{kind:'test',result:{exit_code:1,command:'false',output:'<script>unsafe()</script>',directory:'agent/output/test'}}]);
assert.match(log.textContent,/Step 1 · codex/);assert.match(log.textContent,/Verification · Failed/);
assert(!log.textContent.includes('<score>'));assert(!log.querySelector('script'));assert.equal(log.querySelector('details').open,false);
const snapshot={kind:'request',step:1,provider:'test',context_policy:'files_and_recent_ai',context_note:'Complete selected project files and latest output only.',project_files:['src/a.js','src/lib/b.js','readme.md'],project_file_tokens:[{path:'src/a.js',tokens:1704},{path:'src/lib/b.js',tokens:80},{path:'readme.md',tokens:10}]};
snapshot.part_tokens={context:1794,context_text:1794,context_images:0,prompt:10,system:20,instructions:30,recent_ai:0,total:1854};
snapshot.prompt='Build the fixture';snapshot.system='System';snapshot.instructions='Use tagged Markdown';snapshot.context_directory='.';snapshot.output_directory='agent/output/session/iteration';snapshot.history_turns=3;snapshot.images=0;
const treeLog=w.renderAgentEvents([snapshot,{kind:'model',step:1,provider:'test'}],'tree');
assert.equal(treeLog.querySelector('.iteration-message').firstChild.className,'event-step');
assert.equal(treeLog.querySelectorAll('.event-step').length,1);
assert.match(treeLog.textContent,/Context files sent to AI · 1,794 estimated tokens/);
assert(!treeLog.textContent.includes('Additional context and evidence'));
assert.match(treeLog.textContent,/1,854 estimated tokens/);
assert.match(treeLog.querySelector('.context-tree-folder > summary').textContent,/src1,784 tokens/);
assert.match(treeLog.querySelector('.context-tree-file').textContent,/a.js1,704 tokens/);
assert.match(treeLog.textContent,/File content subtotal: 1,794 estimated tokens/);
w.document.body.append(treeLog);
const folder=treeLog.querySelector('.context-tree-folder');folder.open=true;folder.dispatchEvent(new w.Event('toggle'));
assert.equal(w.renderAgentEvents([snapshot],'tree').querySelector('.context-tree-folder').open,true);
const recentSnapshot={...snapshot,context_policy:'files_and_recent_ai',recent_ai_messages:['Built the app. Tool shell: passed','Verified persistence.'],part_tokens:{context:1794,context_text:1794,context_images:0,recent_ai:15,recent_ai_messages:[10,5],prompt:10,system:20,instructions:30,total:1869}};
const recentLog=w.renderAgentEvents([recentSnapshot],'recent-window');
assert.match(recentLog.textContent,/Previous AI messages · 15 estimated tokens/);
assert.match(recentLog.textContent,/AI message 1 of 2 · 10 estimated tokens/);
assert.match(recentLog.textContent,/AI message 2 of 2 · 5 estimated tokens/);
assert(!recentLog.textContent.includes('Additional context and evidence'));
const tagged=w.renderAgentEvents([{kind:'text',text:'<review>Review the current app.</review>\n<summary>Keep the build handoff.</summary>\n<scores>6</scores>\n<plan>Run the build.</plan>\n<bash>npm test > "$LESSAGENT_OUTPUT_DIR/test.log" 2>&1</bash>\n<python>print("check")</python>\n<done>false</done>'}],'tagged');
assert.equal(tagged.querySelectorAll('.agent-tag').length,7);
assert.match(tagged.textContent,/Review the current app.|Keep the build handoff.|Score · 6\/10|Run the build.|npm test|print\("check"\)|Not done/);
assert(tagged.querySelector('.agent-tag-code'));
assert(!tagged.textContent.includes('<scores>'));
const iterations=w.renderAgentEvents([{kind:'model',step:1,provider:'codex'}, {kind:'text',text:'First reply'}, {kind:'usage',source:'generation',model:'test',usage:{input_tokens:70,output_tokens:20,cached_input_tokens:30}}, {kind:'model',step:2,provider:'codex'}, {kind:'text',text:'Second reply'}, {kind:'usage',source:'generation',model:'test',usage:null}], 'group-test');
assert.equal(iterations.querySelectorAll('.iteration-message').length,2);
assert.match(iterations.children[0].textContent,/First reply/);
assert(!iterations.children[0].textContent.includes('Second reply'));
assert.match(iterations.children[0].textContent,/Input \(excluding cached\): 70 · Output: 20 · Cached input: 30/);
assert.match(iterations.children[1].textContent,/Token usage unavailable/);
assert.match(w.taskMetrics({usage:{input_tokens:140,output_tokens:40,cached_input_tokens:60}}),/Task total/);
console.log('PASS: Agent session isolation, separate drafts, request details expansion, automatic model discovery, new Agent menu');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
