const {JSDOM}=require('jsdom');
const fs=require('fs'),assert=require('node:assert/strict');
const w=new JSDOM('<div id="login-dialog"></div><div id="connection"></div>',{runScripts:'outside-only',url:'http://localhost'}).window;
const source=fs.readFileSync('web/app.js','utf8');
w.document.hasFocus=()=>true;
Object.defineProperty(w.document,'hidden',{value:false});
w.eval(source.slice(source.indexOf('function uiActive()'),source.indexOf('function resumeUi()')));
w.crypto.randomUUID=require('node:crypto').randomUUID;
w.$=s=>w.document.querySelector(s);w.polling=false;w.selected='project';w.viewKey='';
w.state={workspaces:[{id:'project',ui:{active:'chat',tabs:[{id:'chat',kind:'chat'},{id:'files',kind:'files'}]}}]};
w.workspace=()=>w.state.workspaces[0];w.ui=()=>w.workspace().ui;
w.saveUi=async()=>{};w.render=()=>{};w.refreshUsage=()=>{};w.notice=e=>{throw e;};
w.eval(source.slice(source.indexOf('async function closeTab('),source.indexOf('async function scan(')));
w.startupAgentOpened=false;
w.eval(source.slice(source.indexOf('async function poll()'),source.indexOf('$("#add-workspace").onclick')));
w.retainLocalTabs=s=>s;w.api=async()=>w.state;
let opens=0;w.openTab=async(kind,title,extra)=>{opens++;assert.equal(kind,'chat');assert.match(extra.id,/^agent-/);};
(async()=>{try{
await w.closeTab('chat');assert.equal(w.ui().active,'files');assert.equal(w.ui().tabs.length,1);
await w.closeTab('files');assert.equal(w.ui().active,null);assert.equal(w.ui().tabs.length,0);
await w.poll();await w.poll();assert.equal(opens,1);
w.eval(source.slice(source.indexOf('async function openTab('),source.indexOf('async function closeTab(')));
w.ui().tabs=[{id:'chat',kind:'chat'},{id:'file:a',kind:'file'},{id:'term',kind:'terminal'},{id:'agent-old',kind:'chat'},{id:'files',kind:'files'}];
await w.openTab('chat','Agent',{id:'agent-new'});
assert.deepEqual(Array.from(w.ui().tabs,t=>t.id),['chat','term','agent-old','agent-new','file:a','files']);
await w.openTab('file','b',{id:'file:b'});
assert.equal(w.ui().tabs.at(-1).id,'file:b');
await w.openTab('chat','Agent',{id:'agent-next'});
assert.equal(w.ui().tabs.findIndex(t=>t.id==='agent-next'),w.ui().tabs.findIndex(t=>t.id==='agent-new')+1);
console.log('PASS: default Agent closes, empty tabs stay empty, startup opens one fresh Agent');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
