const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const w=new JSDOM('<main></main>',{runScripts:'outside-only'}).window;
const source=fs.readFileSync('web/app.js','utf8');
w.document.hasFocus=()=>true;
Object.defineProperty(w.document,'hidden',{value:false});
w.eval(source.slice(source.indexOf('function uiActive()'),source.indexOf('function resumeUi()')));
w.el=(tag,cls,text)=>{const n=w.document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
w.button=(text,fn)=>{const n=w.el('button','',text);n.onclick=fn;return n;};w.iconButton=w.button;w.guard=fn=>fn;w.notice=e=>{throw e;};
w.formatTokens=n=>n+' tokens';w.formatBytes=n=>n+' bytes';
w.toolbar=(title,...actions)=>{const n=w.el('header','',title);n.append(...actions);return n;};
w.HTMLDialogElement.prototype.show=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;this.onclose?.();};
const opens=[];w.openTab=async(...args)=>opens.push(args);
w.api=async(path)=>path.includes('inventory')?{files:[]}:{headers:{get:()=> 'text/plain'},text:async()=>'<script>safe text</script>'};
w.act=async()=>({entries:[{name:'file.txt',path:'/project/file.txt',directory:false,kind:'text',bytes:12}]});
w.eval(source.slice(source.indexOf('async function previewFile('),source.indexOf('async function renderFile(')));
w.eval(source.slice(source.indexOf('function createFileBrowser('),source.indexOf('const gitViews')));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{try{
const browser=w.createFileBrowser({workspaceId:'w',root:'/project'});w.document.body.append(browser);await delay(10);
const row=browser.querySelector('.tree-row');assert(row);
await row.onclick();await delay(280);
assert.equal(opens.length,0);assert(w.document.querySelector('.file-preview-popup'));
assert.equal(w.document.querySelector('.file-preview-body pre').textContent,'<script>safe text</script>');
assert.equal(w.document.querySelector('.file-preview-body script'),null);
await row.onclick();await row.ondblclick();await delay(280);
assert.equal(opens.length,1);assert.equal(opens[0][2].path,'file.txt');assert.equal(w.document.querySelector('.file-preview-popup'),null);
await w.previewFile('w','file.txt','text');
const buttons=w.document.querySelectorAll('.file-preview-popup button');await buttons[0].onclick();
assert.equal(opens.length,2);assert.equal(w.document.querySelector('.file-preview-popup'),null);
// Project Context browses excluded entries too, but ranks included tokens first.
browser.remove();
w.api=async()=>({files:[{path:'small/a.txt',tokens:5,bytes:1},{path:'big.txt',tokens:500,bytes:5}],total_tokens:505,text_tokens:505,image_tokens:0});
w.act=async()=>({entries:[{name:'ignored.txt',path:'/project/ignored.txt',directory:false,bytes:12},{name:'small',path:'/project/small',directory:true},{name:'big.txt',path:'/project/big.txt',directory:false,bytes:5}]});
const context=w.createFileBrowser({workspaceId:'w',root:'/project',context:true});w.document.body.append(context);await delay(10);
assert.deepEqual(Array.from(context.querySelectorAll('.tree-row'),r=>r.dataset.path),['/project/big.txt','/project/small','/project/ignored.txt']);
assert.equal(context.querySelector('.context-excluded').dataset.path,'/project/ignored.txt');
assert.match(context.querySelector('.context-excluded').textContent,/Not included/);
context.remove();
w.api=async()=>({files:[]});
w.act=async({})=>({entries:[{name:'output',path:'/project/output',directory:true}]});
const output=w.createFileBrowser({workspaceId:'w',root:'/project'});w.document.body.append(output);await delay(10);
w.act=async()=>({path:'/project/output',entries:[{name:'old',path:'/project/output/old',directory:true,modified_ms:10},{name:'new.txt',path:'/project/output/new.txt',directory:false,modified_ms:30},{name:'middle',path:'/project/output/middle',directory:true,created_ms:20}]});
await output.querySelector('.tree-row').ondblclick();
assert.deepEqual(Array.from(output.querySelectorAll('.tree-row'),r=>r.dataset.path),['/project/output/new.txt','/project/output/middle','/project/output/old']);
console.log('PASS: single click previews safely; double click opens one tab; popup open action works');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
