const {JSDOM}=require('jsdom');
const fs=require('fs'), assert=require('node:assert/strict');
const dom=new JSDOM('<main id="view"></main>',{runScripts:'outside-only'}), w=dom.window;
const source=fs.readFileSync('web/app.js','utf8');
w.eval(source.slice(source.indexOf('function cleanAgentText('),source.indexOf('function toolbar(')));
w.eval(source.slice(source.indexOf('const gitViews')));
w.$=s=>w.document.querySelector(s);
w.el=(tag,cls,text)=>{const n=w.document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
w.button=(text,fn,cls)=>{const n=w.el('button',cls,text);n.onclick=fn;return n;};
w.input=()=>w.el('input');w.toolbar=title=>w.el('h2','',title);
w.selected='workspace'; w.viewKey='workspace/git';w.ui=()=>({tabs:[{id:'git',kind:'git'}],active:'git'});
const job={id:'one',workspace:'workspace',prompt:'A long prompt with enough characters to truncate',status:'completed',started:1700000000000,output:'Done',events:[],usage:{input_tokens:40,output_tokens:9,cached_input_tokens:60},elapsed_ms:1234};
w.state={jobs:[job,{...job,id:'other',workspace:'other'}]};let opened;
w.openTab=(...args)=>opened=args;
(async()=>{try {
assert.equal(w.shortTabTitle('a'.repeat(25)),'a'.repeat(25));
assert.equal(w.shortTabTitle('123456789012345middleabcdefghij'),'123456789012345…abcdefghij');
assert.equal(w.shortTabTitle('😀'.repeat(26)), '😀'.repeat(15)+'…'+'😀'.repeat(10));
w.renderHistory();assert.equal(w.document.querySelectorAll('.history-session').length,1);
w.document.querySelector('.history-session').click();assert.equal(opened[2].jobId,'one');
w.renderSession({jobId:'one'});assert.match(w.document.body.textContent,/excluding cached.*40.*Output: 9.*Cached input: 60.*1.23 s/);
w.act=async(action)=> action==='git_status' ? {branch:'main',branches:[{ref:'refs/heads/main',name:'main',commit:'abc',subject:'initial',date:'today'},{ref:'refs/heads/feature',name:'feature',commit:'def',subject:'feature',date:'today'}],files:[{path:'app.js',status:' M',added:3,deleted:2}]} : action==='git_file' ? {unstaged:'@@ -1 +1 @@\n-old\n+new',staged:'',untracked:''} : {ahead:1,behind:0,diff:'+feature'};
await w.renderGit();assert.match(w.document.body.textContent,/Current branch: main/);assert.equal(w.document.querySelectorAll('[role=tab]').length,2);
assert.match(w.document.body.textContent,/\+3 −2/);
w.document.querySelector('.git-file').click();await new Promise(r=>setImmediate(r));assert.match(w.document.body.textContent,/-old.*\+new/);
[...w.document.querySelectorAll('[role=tab]')].find(b=>b.textContent.startsWith('Branches')).click();
assert.equal(w.document.querySelectorAll('.git-branch').length,2);
w.document.querySelectorAll('.git-branch')[1].click();await new Promise(r=>setImmediate(r));
assert.match(w.document.body.textContent,/1 commits ahead.*Changes from main to feature.*\+feature/);
assert.ok([...w.document.querySelectorAll('button')].find(b=>b.textContent==='Switch to this branch' && !b.disabled));
[...w.document.querySelectorAll('[role=tab]')].find(b=>b.textContent.startsWith('Changes')).click();
assert.match(w.document.body.textContent,/Discard all changes/);
await new Promise(r=>setImmediate(r));
console.log('PASS: tab title boundaries, Unicode, history isolation, session metrics, Git rendering');
} finally {w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
