const {JSDOM}=require('jsdom');
const fs=require('fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<footer><span id="provider-label"></span><span></span></footer><form><textarea>test task</textarea><button type="button">Send</button></form>',{runScripts:'outside-only'}),w=dom.window;
const source=fs.readFileSync('web/app.js','utf8');
w.document.hasFocus=()=>true;
Object.defineProperty(w.document,'hidden',{value:false});
w.eval(source.slice(source.indexOf('function uiActive()'),source.indexOf('function resumeUi()')));
w.eval(source.slice(source.indexOf('let usageSnapshot')));
w.el=(tag,cls,text)=>{const n=w.document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
w.guard=f=>(...a)=>Promise.resolve(f(...a)).catch(e=>{throw e;});
w.state={settings:{provider:'codex',model:'fixture',thinking:'medium'},jobs:[{workspace:'one',score:9.5,status:'completed'}]};w.ui=()=>({tabs:[],active:'chat'});w.selected='one';
w.api=async()=>[{id:'fixture',details:{supported_reasoning_levels:[{effort:'low'},{effort:'medium'},{effort:'high'}]}}];
let sent=0,requests=[];w.act=async(action,body)=>{requests.push({action,body});return {rate_limit:{primary_window:{used_percent:12},secondary_window:{used_percent:43}}};};
const form=w.document.querySelector('form'),send=w.document.querySelector('button');form.requestSubmit=()=>{sent++;};
const tick=()=>new Promise(r=>setImmediate(r));
const pointer=(target,type)=>target.dispatchEvent(new w.MouseEvent(type,{bubbles:true,button:0,clientX:0,clientY:0}));
(async()=>{try{
w.installThinkingSend(send,form);await tick();
pointer(send,'pointerdown');assert.ok(w.document.querySelector('.thinking-menu'));
w.document.elementFromPoint=()=>w.document.querySelector('[data-level="high"]');pointer(w.document,'pointermove');pointer(w.document,'pointerup');await tick();
assert.equal(sent,1);assert.equal(w.state.settings.thinking,'high');assert.equal(requests[0].body.thinking,'high');
pointer(send,'pointerdown');w.document.elementFromPoint=()=>send;pointer(w.document,'pointerup');await tick();assert.equal(sent,1);
await new Promise(r=>setTimeout(r,3100));assert.equal(sent,2);assert.equal(w.document.querySelector('.thinking-menu'),null);
pointer(send,'pointerdown');pointer(w.document,'pointerup');w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));await new Promise(r=>setTimeout(r,3100));assert.equal(sent,2);
pointer(send,'pointerdown');w.document.elementFromPoint=()=>send;pointer(w.document,'pointerup');
const low=w.document.querySelector('[data-level="low"]');
assert.equal(low.textContent,'low');
assert(!w.document.querySelector('.thinking-menu').textContent.includes('Choose thinking'));
pointer(low,'pointerdown');pointer(low,'pointerup');await tick();
assert.equal(sent,3);assert.equal(w.state.settings.thinking,'low');
pointer(send,'pointerdown');pointer(w.document,'pointerup');
w.document.querySelector('[data-level="high"]').click();await tick();
assert.equal(sent,4);assert.equal(w.state.settings.thinking,'high');
await w.refreshUsage();assert.match(w.document.querySelector('footer').textContent,/fixture-high.*Score: 9.5\/10.*5h: 88% left.*Week: 57% left/);
const formats=source.slice(source.indexOf('const formatTokens'),source.indexOf('function showMenu'));
w.eval(formats+'\nwindow.ft=formatTokens;window.fb=formatBytes;');
assert.match(w.ft(150000),/0.15M/);assert.match(w.fb(150000),/0.15 MB/);
console.log('PASS: thinking drag/release, three-second click delay, cancel, saved effort, score/usage footer, M units');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
